dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^6.0.6
  flutter_launcher_icons: ^0.9.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  android: true
  ios: true
  image_path: cd Downloads OP.png